version: '2'
services:
  production:
    build:
      context: .
    env_file: .env
    environment:
      - MONGODB_URI=mongodb://db:27017/wi-sessions-db
      - NODE_ENV=production
      - PORT=5000
    ports:
      - '5000:5000'
    restart: always
    container_name: wi-app-prod
    links:
      - db
    depends_on:
      - db
  db:
    image: mongo:latest
    restart: always
    container_name: wi-mongo
    # volumes:
    #   - './data/wi-mongo/:/data/db'
