apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  labels:
    name: nginx-conf
  namespace: default
data:
  default.conf: |-
    server {
      listen 80;

      server_name _;

      location / {
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_redirect off;
        proxy_pass http://localhost:3000;
      }
    }
